In [ ]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import re
import csv

In [ ]:
url = 'https://sso.agc.gov.sg/Act/TSFA2002?ProvIds=Sc1-#Sc1-'
headers = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"}

response = requests.get(url=url, headers=headers)


print(response)

<Response [200]>

In [ ]:

soup = BeautifulSoup(response.content, "html.parser")

table = soup.find_all("table", {"class": "p1_1"})
input_str = []


# Print the text
#print(table[1])
tab = table[1].find_all("td",{'class':"sProvP1"})
for text in tab:
    input_str.append(text.get_text())

print(input_str[0:3])

['Haji Ibrahim B Haji Maidin (Singapore citizen) (Date of Birth: 1 October 1950);', 'Alahuddeen bin Abdullah (Singapore citizen) (Date of Birth: 27 May 1967);', 'Mohammad Aslam bin Yar Ali Khan (Singapore citizen) (Date of Birth: 19 October 1964);']

In [ ]:
with open('output.csv', mode='w', newline='') as file:
    # Create a CSV writer object
    writer = csv.writer(file)
    
    # Write the header row
    writer.writerow(['Name', 'Citizenship', 'Date of Birth'])
    
    # Iterate over the data and write each row
    for item in input_str:
        # Split the string into its components
        name, citizenship, dob = item.split('(')[0].strip(), item.split('(')[1].split(')')[0], item.split(':')[1].strip()[:-1]
        
        # Write the row to the CSV file
        writer.writerow([name, citizenship, dob])

In [ ]:
name =[]
citizenships =[]
dob= []

for item in input_str:
    # Split the string into its components
    n, c, d = item.split('(')[0].strip(), item.split('(')[1].split(')')[0], item.split(':')[1].strip()[:-1]
    name.append(n)
    citizenships.append(c)
    dob.append(d)
print(name)
print(citizenships)
print(dob)

['Haji Ibrahim B Haji Maidin', 'Alahuddeen bin Abdullah', 'Mohammad Aslam bin Yar Ali Khan', 'Mas Selamat bin Kastari', 'Abd Rahim bin Abdul Rahman', 'Husaini bin Ismail', 'Asyrani bin Hussaini', 'Masyhadi bin Mas Selamat', 'Mohamed Hassan bin Saynudin', 'Muhamad Ali s/o Abdul Rahiman', 'Haja Fakkurudeen Usman Ali', 'M Arifil Azim Putra Norja’i', 'Mustafa bin Sultan Ali', 'Muhammad Shamin bin Mohamed Sidek', 'Rahman Mizanur', 'Mamun Leakot Ali', 'Sohag Ibrahim', 'Miah Rubel', 'Zzaman Daulat', 'Sohel Hawlader Ismail Hawlader', 'Md Jabath Kysar Haje Norul Islam Sowdagar', 'Islam Shariful', 'Mohamad Shariff Zulfikar', 'Muhammad Fadil bin Abdul Hamid', 'Rosli bin Hamzah', 'Mohamed Omar bin Mahadi', 'Syaikhah Izzah Zahrah al-Ansari', 'Muhammad Khairul Bin Mohamed', 'Imran Kassim', 'Megat Shahdan bin Abdul Samad', 'Maimunah Binti Abdul Kadir', 'Abu Thalha Bin Samad', 'Ahmed Hussein Abdul Kadir s/o Sheik Uduman', 'Mohamed Kazali bin Salleh', 'Mohamed Faishal bin Mohd Razali', 'Hazim Syahmi Bin Mahfoot', 'Imran bin Mahmood', 'Kuthubdeen Haja Najumudeen', 'Suderman bin Samikin', 'Anindia Afiyantari @ Anin Dia Afiyan Tari', 'Retno Hernayani', 'Turmini', 'Sheik Heikel bin Khalid Bafana', 'Ahmed Faysal', 'Amirull bin Ali', 'Ruqayyah binti Ramli']
['Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Bangladesh citizen', 'Australia citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Singapore citizen', 'Indonesian citizen', 'Indonesian citizen', 'Indonesian citizen', 'Singapore citizen', 'Bangladesh citizen', 'Singapore citizen', 'Singapore citizen']
['1 October 1950)', '27 May 1967)', '19 October 1964)', '23 January 1961)', '19 October 1968)', '30 December 1958)', '16 May 1989)', '8 January 1989)', '3 November 1973)', '14 January 1965)', '30 July 1976)', '29 November 1995)', '1 September 1963)', '8 September 1986)', '15 March 1985)', '1 August 1986)', '26 July 1988)', '12 December 1989)', '10 February 1982)', '6 June 1986)', '17 May 1985)', '3 January 1989)', '28 September 1971)', '7 July 1989)', '3 May 1966)', '12 December 1982)', '31 December 1994)', '30 August 1992)', '22 June 1983)', '29 August 1978)', '17 March 1968)', '14 November 1991)', '4 October 1984)', '25 July 1970)', '5 September 1990)', '2 August 1990)', '15 August 1978)', '13 February 1983)', '17 July 1972)', '10 April 1987) (Work Permit No.\xa0G6545158T stating Date of Birt', '30 December 1982)', '22 June 1988)', '29 January 1972)', '14 May 1994)', '23 March 2000)', '15 June 1986)']

In [ ]:
hii = pd.read_csv("/content/output.csv")
hii.head(10)

,Name,Citizenship,Date of Birth
0,Haji Ibrahim B Haji Maidin,Singapore citizen,1 October 1950)
1,Alahuddeen bin Abdullah,Singapore citizen,27 May 1967)
2,Mohammad Aslam bin Yar Ali Khan,Singapore citizen,19 October 1964)
3,Mas Selamat bin Kastari,Singapore citizen,23 January 1961)
4,Abd Rahim bin Abdul Rahman,Singapore citizen,19 October 1968)
5,Husaini bin Ismail,Singapore citizen,30 December 1958)
6,Asyrani bin Hussaini,Singapore citizen,16 May 1989)
7,Masyhadi bin Mas Selamat,Singapore citizen,8 January 1989)
8,Mohamed Hassan bin Saynudin,Singapore citizen,3 November 1973)
9,Muhamad Ali s/o Abdul Rahiman,Singapore citizen,14 January 1965)
10,Haja Fakkurudeen Usman Ali,Singapore citizen,30 July 1976)
11,M Arifil Azim Putra Norja’i,Singapore citizen,29 November 1995)
12,Mustafa bin Sultan Ali,Singapore citizen,1 September 1963)
13,Muhammad Shamin bin Mohamed Sidek,Singapore citizen,8 September 1986)
14,Rahman Mizanur,Bangladesh citizen,15 March 1985)
15,Mamun Leakot Ali,Bangladesh citizen,1 August 1986)
16,Sohag Ibrahim,Bangladesh citizen,26 July 1988)
17,Miah Rubel,Bangladesh citizen,12 December 1989)
18,Zzaman Daulat,Bangladesh citizen,10 February 1982)
19,Sohel Hawlader Ismail Hawlader,Bangladesh citizen,6 June 1986)
20,Md Jabath Kysar Haje Norul Islam Sowdagar,Bangladesh citizen,17 May 1985)
21,Islam Shariful,Bangladesh citizen,3 January 1989)
22,Mohamad Shariff Zulfikar,Australia citizen,28 September 1971)
23,Muhammad Fadil bin Abdul Hamid,Singapore citizen,7 July 1989)
24,Rosli bin Hamzah,Singapore citizen,3 May 1966)
25,Mohamed Omar bin Mahadi,Singapore citizen,12 December 1982)
26,Syaikhah Izzah Zahrah al-Ansari,Singapore citizen,31 December 1994)
27,Muhammad Khairul Bin Mohamed,Singapore citizen,30 August 1992)
28,Imran Kassim,Singapore citizen,22 June 1983)
29,Megat Shahdan bin Abdul Samad,Singapore citizen,29 August 1978)
30,Maimunah Binti Abdul Kadir,Singapore citizen,17 March 1968)
31,Abu Thalha Bin Samad,Singapore citizen,14 November 1991)
32,Ahmed Hussein Abdul Kadir s/o Sheik Uduman,Singapore citizen,4 October 1984)
33,Mohamed Kazali bin Salleh,Singapore citizen,25 July 1970)
34,Mohamed Faishal bin Mohd Razali,Singapore citizen,5 September 1990)
35,Hazim Syahmi Bin Mahfoot,Singapore citizen,2 August 1990)
36,Imran bin Mahmood,Singapore citizen,15 August 1978)
37,Kuthubdeen Haja Najumudeen,Singapore citizen,13 February 1983)
38,Suderman bin Samikin,Singapore citizen,17 July 1972)
39,Anindia Afiyantari @ Anin Dia Afiyan Tari,Indonesian citizen,10 April 1987) (Work Permit No. G6545158T stat...
40,Retno Hernayani,Indonesian citizen,30 December 1982)
41,Turmini,Indonesian citizen,22 June 1988)
42,Sheik Heikel bin Khalid Bafana,Singapore citizen,29 January 1972)
43,Ahmed Faysal,Bangladesh citizen,14 May 1994)
44,Amirull bin Ali,Singapore citizen,23 March 2000)
45,Ruqayyah binti Ramli,Singapore citizen,15 June 1986)